export const REQUEST_FILES = 'REQUEST_FILES';
export const RECEIVE_FILES = 'RECEIVE_FILES';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const RECEIVE_UPLOADED_FILE = 'RECEIVE_UPLOADED_FILE';
export const DELETE_FILE = 'DELETE_FILE';
export const RECEIVE_DELETED_FILE = 'RECEIVE_DELETED_FILE';
